/**
 * Feature upsert helpers — extracted from `api/cron/build-features.ts`
 * during the Phase 4c refactor (api-refactor-2026-05-02).
 *
 * Scope: pure schema mapping for `training_features` — the column list,
 * the COALESCE-on-every-column UPSERT, the nullable-key set, and the
 * `computeCompleteness` calculator. Behaviour unchanged — the cron
 * handler used to own this verbatim and just imports it now.
 *
 * Why COALESCE on every column: the fail-soft helpers in
 * build-features-phase2.ts (and friends) return `undefined` for any
 * field whose upstream API call failed (e.g. UW returning 403 for dates
 * outside its 30-day rolling window). Those undefineds become NULL in
 * the parameterized statement; without COALESCE, every backfill would
 * clobber a previously-fetched value with NULL.
 */
import { getDb } from './db.js';
import type { FeatureRow } from './build-features-types.js';

// ── Nullable feature keys ──────────────────────────────────────
//
// Columns that are legitimately null on most days (non-event days, no
// significant gamma wall, futures features prior to sidecar liveness,
// etc.). Excluding them from the completeness denominator prevents the
// score from being artificially penalised by features that genuinely
// don't apply.
export const NULLABLE_FEATURE_KEYS = new Set([
  'event_type',
  'is_opex',
  'gamma_wall_above_dist',
  'gamma_wall_above_mag',
  'gamma_wall_below_dist',
  'gamma_wall_below_mag',
  'neg_gamma_nearest_dist',
  'neg_gamma_nearest_mag',
  'gamma_asymmetry',
  'charm_max_pos_dist',
  'charm_max_neg_dist',
  'dp_total_premium',
  'dp_cluster_count',
  'dp_top_cluster_dist',
  'dp_support_premium',
  'dp_resistance_premium',
  'dp_support_resistance_ratio',
  'dp_concentration',
  'max_pain_0dte',
  'max_pain_dist',
  'opt_call_volume',
  'opt_put_volume',
  'opt_call_oi',
  'opt_put_oi',
  'opt_call_premium',
  'opt_put_premium',
  'opt_bullish_premium',
  'opt_bearish_premium',
  'opt_call_vol_ask',
  'opt_put_vol_bid',
  'opt_vol_pcr',
  'opt_oi_pcr',
  'opt_premium_ratio',
  'opt_call_vol_vs_avg30',
  'opt_put_vol_vs_avg30',
  'iv_open',
  'iv_max',
  'iv_range',
  'iv_crush_rate',
  'iv_spike_count',
  'iv_at_t2',
  'pcr_open',
  'pcr_max',
  'pcr_min',
  'pcr_range',
  'pcr_trend_t1_t2',
  'pcr_spike_count',
  'oic_net_oi_change',
  'oic_call_oi_change',
  'oic_put_oi_change',
  'oic_oi_change_pcr',
  'oic_net_premium',
  'oic_call_premium',
  'oic_put_premium',
  'oic_ask_ratio',
  'oic_multi_leg_pct',
  'oic_top_strike_dist',
  'oic_concentration',
  'iv_ts_slope_0d_30d',
  'iv_ts_contango',
  'iv_ts_spread',
  'uw_rv_30d',
  'uw_iv_rv_spread',
  'uw_iv_overpricing_pct',
  'iv_rank',
  // Futures features — nullable until sidecar is live
  'es_momentum_t1',
  'es_momentum_t2',
  'es_spx_basis_t1',
  'es_volume_ratio_t1',
  'es_overnight_range',
  'es_overnight_gap',
  'es_gap_fill_pct_t1',
  'es_vwap_deviation_t1',
  'nq_momentum_t1',
  'nq_es_ratio_t1',
  'nq_es_ratio_change',
  'nq_qqq_divergence_t1',
  'vx_front_price',
  'vx_term_spread',
  'vx_term_slope_pct',
  'vx_contango_signal',
  'vx_basis',
  'zn_momentum_t1',
  'zn_daily_change',
  'spx_zn_correlation_5d',
  'rty_momentum_t1',
  'rty_es_divergence_t1',
  'cl_overnight_change_pct',
  'cl_intraday_momentum_t1',
  'cl_es_correlation_5d',
  'es_put_oi_concentration',
  'es_call_oi_concentration',
  'es_options_max_pain_dist',
  'es_spx_gamma_agreement',
  'es_put_buy_aggressor_pct',
  'es_call_buy_aggressor_pct',
  'es_options_net_delta',
  'es_atm_iv',
]);

/** Compute feature completeness as fraction of non-null values. */
export function computeCompleteness(features: FeatureRow): number {
  const keys = Object.keys(features).filter(
    (k) =>
      k !== 'date' &&
      k !== 'feature_completeness' &&
      k !== 'created_at' &&
      !NULLABLE_FEATURE_KEYS.has(k),
  );
  if (keys.length === 0) return 0;
  const nonNull = keys.filter((k) => features[k] != null).length;
  return Math.round((nonNull / keys.length) * 100) / 100;
}

// ── Upsert ──────────────────────────────────────────────────────

export async function upsertFeatures(f: FeatureRow): Promise<void> {
  const sql = getDb();
  await sql`
    INSERT INTO training_features (
      date, vix, vix1d, vix9d, vvix, vix1d_vix_ratio, vix_vix9d_ratio,
      regime_zone, cluster_mult, dow_mult, dow_label,
      spx_open, sigma, hours_remaining,
      ic_ceiling, put_spread_ceiling, call_spread_ceiling,
      opening_range_signal, opening_range_pct_consumed,
      day_of_week, is_friday, is_event_day,
      mt_ncp_t1, mt_npp_t1, mt_ncp_t2, mt_npp_t2,
      mt_ncp_t3, mt_npp_t3, mt_ncp_t4, mt_npp_t4,
      spx_ncp_t1, spx_npp_t1, spx_ncp_t2, spx_npp_t2,
      spx_ncp_t3, spx_npp_t3, spx_ncp_t4, spx_npp_t4,
      spy_ncp_t1, spy_npp_t1, spy_ncp_t2, spy_npp_t2,
      qqq_ncp_t1, qqq_npp_t1, qqq_ncp_t2, qqq_npp_t2,
      spy_etf_ncp_t1, spy_etf_npp_t1, spy_etf_ncp_t2, spy_etf_npp_t2,
      qqq_etf_ncp_t1, qqq_etf_npp_t1, qqq_etf_ncp_t2, qqq_etf_npp_t2,
      zero_dte_ncp_t1, zero_dte_npp_t1, zero_dte_ncp_t2, zero_dte_npp_t2,
      delta_flow_total_t1, delta_flow_dir_t1, delta_flow_total_t2, delta_flow_dir_t2,
      flow_agreement_t1, flow_agreement_t2,
      etf_tide_divergence_t1, etf_tide_divergence_t2,
      ncp_npp_gap_spx_t1, ncp_npp_gap_spx_t2,
      gex_oi_t1, gex_oi_t2, gex_oi_t3, gex_oi_t4,
      gex_vol_t1, gex_vol_t2, gex_dir_t1, gex_dir_t2,
      gex_oi_slope, charm_oi_t1, charm_oi_t2,
      agg_net_gamma, dte0_net_charm, dte0_charm_pct,
      gamma_wall_above_dist, gamma_wall_above_mag,
      gamma_wall_below_dist, gamma_wall_below_mag,
      neg_gamma_nearest_dist, neg_gamma_nearest_mag,
      gamma_asymmetry, charm_slope,
      charm_max_pos_dist, charm_max_neg_dist,
      gamma_0dte_allexp_agree, charm_pattern,
      feature_completeness,
      prev_day_range_pts, prev_day_direction, prev_day_vix_change, prev_day_range_cat,
      realized_vol_5d, realized_vol_10d, rv_iv_ratio,
      vix_term_slope, vvix_percentile,
      event_type, is_fomc, is_opex, days_to_next_event, event_count,
      dp_total_premium, dp_cluster_count, dp_top_cluster_dist,
      dp_support_premium, dp_resistance_premium,
      dp_support_resistance_ratio, dp_concentration,
      max_pain_0dte, max_pain_dist,
      opt_call_volume, opt_put_volume, opt_call_oi, opt_put_oi,
      opt_call_premium, opt_put_premium,
      opt_bullish_premium, opt_bearish_premium,
      opt_call_vol_ask, opt_put_vol_bid,
      opt_vol_pcr, opt_oi_pcr, opt_premium_ratio,
      opt_call_vol_vs_avg30, opt_put_vol_vs_avg30,
      iv_open, iv_max, iv_range, iv_crush_rate, iv_spike_count, iv_at_t2,
      pcr_open, pcr_max, pcr_min, pcr_range, pcr_trend_t1_t2, pcr_spike_count,
      oic_net_oi_change, oic_call_oi_change, oic_put_oi_change,
      oic_oi_change_pcr, oic_net_premium, oic_call_premium, oic_put_premium,
      oic_ask_ratio, oic_multi_leg_pct, oic_top_strike_dist, oic_concentration,
      iv_ts_slope_0d_30d, iv_ts_contango, iv_ts_spread,
      uw_rv_30d, uw_iv_rv_spread, uw_iv_overpricing_pct, iv_rank,
      nope_t1, nope_t2, nope_t3, nope_t4,
      nope_am_mean, nope_am_sign_flips, nope_am_cum_delta
    ) VALUES (
      ${f.date}, ${f.vix}, ${f.vix1d}, ${f.vix9d}, ${f.vvix},
      ${f.vix1d_vix_ratio}, ${f.vix_vix9d_ratio},
      ${f.regime_zone}, ${f.cluster_mult}, ${f.dow_mult}, ${f.dow_label},
      ${f.spx_open}, ${f.sigma}, ${f.hours_remaining},
      ${f.ic_ceiling}, ${f.put_spread_ceiling}, ${f.call_spread_ceiling},
      ${f.opening_range_signal}, ${f.opening_range_pct_consumed},
      ${f.day_of_week}, ${f.is_friday}, ${f.is_event_day},
      ${f.mt_ncp_t1}, ${f.mt_npp_t1}, ${f.mt_ncp_t2}, ${f.mt_npp_t2},
      ${f.mt_ncp_t3}, ${f.mt_npp_t3}, ${f.mt_ncp_t4}, ${f.mt_npp_t4},
      ${f.spx_ncp_t1}, ${f.spx_npp_t1}, ${f.spx_ncp_t2}, ${f.spx_npp_t2},
      ${f.spx_ncp_t3}, ${f.spx_npp_t3}, ${f.spx_ncp_t4}, ${f.spx_npp_t4},
      ${f.spy_ncp_t1}, ${f.spy_npp_t1}, ${f.spy_ncp_t2}, ${f.spy_npp_t2},
      ${f.qqq_ncp_t1}, ${f.qqq_npp_t1}, ${f.qqq_ncp_t2}, ${f.qqq_npp_t2},
      ${f.spy_etf_ncp_t1}, ${f.spy_etf_npp_t1}, ${f.spy_etf_ncp_t2}, ${f.spy_etf_npp_t2},
      ${f.qqq_etf_ncp_t1}, ${f.qqq_etf_npp_t1}, ${f.qqq_etf_ncp_t2}, ${f.qqq_etf_npp_t2},
      ${f.zero_dte_ncp_t1}, ${f.zero_dte_npp_t1}, ${f.zero_dte_ncp_t2}, ${f.zero_dte_npp_t2},
      ${f.delta_flow_total_t1}, ${f.delta_flow_dir_t1},
      ${f.delta_flow_total_t2}, ${f.delta_flow_dir_t2},
      ${f.flow_agreement_t1}, ${f.flow_agreement_t2},
      ${f.etf_tide_divergence_t1}, ${f.etf_tide_divergence_t2},
      ${f.ncp_npp_gap_spx_t1}, ${f.ncp_npp_gap_spx_t2},
      ${f.gex_oi_t1}, ${f.gex_oi_t2}, ${f.gex_oi_t3}, ${f.gex_oi_t4},
      ${f.gex_vol_t1}, ${f.gex_vol_t2}, ${f.gex_dir_t1}, ${f.gex_dir_t2},
      ${f.gex_oi_slope}, ${f.charm_oi_t1}, ${f.charm_oi_t2},
      ${f.agg_net_gamma}, ${f.dte0_net_charm}, ${f.dte0_charm_pct},
      ${f.gamma_wall_above_dist}, ${f.gamma_wall_above_mag},
      ${f.gamma_wall_below_dist}, ${f.gamma_wall_below_mag},
      ${f.neg_gamma_nearest_dist}, ${f.neg_gamma_nearest_mag},
      ${f.gamma_asymmetry}, ${f.charm_slope},
      ${f.charm_max_pos_dist}, ${f.charm_max_neg_dist},
      ${f.gamma_0dte_allexp_agree}, ${f.charm_pattern},
      ${f.feature_completeness},
      ${f.prev_day_range_pts}, ${f.prev_day_direction}, ${f.prev_day_vix_change}, ${f.prev_day_range_cat},
      ${f.realized_vol_5d}, ${f.realized_vol_10d}, ${f.rv_iv_ratio},
      ${f.vix_term_slope}, ${f.vvix_percentile},
      ${f.event_type}, ${f.is_fomc}, ${f.is_opex}, ${f.days_to_next_event}, ${f.event_count},
      ${f.dp_total_premium}, ${f.dp_cluster_count}, ${f.dp_top_cluster_dist},
      ${f.dp_support_premium}, ${f.dp_resistance_premium},
      ${f.dp_support_resistance_ratio}, ${f.dp_concentration},
      ${f.max_pain_0dte}, ${f.max_pain_dist},
      ${f.opt_call_volume}, ${f.opt_put_volume},
      ${f.opt_call_oi}, ${f.opt_put_oi},
      ${f.opt_call_premium}, ${f.opt_put_premium},
      ${f.opt_bullish_premium}, ${f.opt_bearish_premium},
      ${f.opt_call_vol_ask}, ${f.opt_put_vol_bid},
      ${f.opt_vol_pcr}, ${f.opt_oi_pcr}, ${f.opt_premium_ratio},
      ${f.opt_call_vol_vs_avg30}, ${f.opt_put_vol_vs_avg30},
      ${f.iv_open}, ${f.iv_max}, ${f.iv_range},
      ${f.iv_crush_rate}, ${f.iv_spike_count}, ${f.iv_at_t2},
      ${f.pcr_open}, ${f.pcr_max}, ${f.pcr_min},
      ${f.pcr_range}, ${f.pcr_trend_t1_t2}, ${f.pcr_spike_count},
      ${f.oic_net_oi_change}, ${f.oic_call_oi_change}, ${f.oic_put_oi_change},
      ${f.oic_oi_change_pcr}, ${f.oic_net_premium}, ${f.oic_call_premium},
      ${f.oic_put_premium}, ${f.oic_ask_ratio}, ${f.oic_multi_leg_pct},
      ${f.oic_top_strike_dist}, ${f.oic_concentration},
      ${f.iv_ts_slope_0d_30d}, ${f.iv_ts_contango}, ${f.iv_ts_spread},
      ${f.uw_rv_30d}, ${f.uw_iv_rv_spread}, ${f.uw_iv_overpricing_pct}, ${f.iv_rank},
      ${f.nope_t1}, ${f.nope_t2}, ${f.nope_t3}, ${f.nope_t4},
      ${f.nope_am_mean}, ${f.nope_am_sign_flips}, ${f.nope_am_cum_delta}
    )
    -- COALESCE on every column: only overwrite when the new value is non-null.
    -- The fail-soft helpers in build-features-phase2.ts return undefined for
    -- any field whose API call failed (e.g. UW returning 403 for dates outside
    -- the 30-day rolling window), and undefined → NULL when interpolated. A
    -- naked EXCLUDED.col assignment would clobber a previously-fetched value
    -- with NULL on every backfill. COALESCE preserves the existing fact when
    -- the re-fetch couldn't produce a fresh one.
    ON CONFLICT (date) DO UPDATE SET
      vix = COALESCE(EXCLUDED.vix, training_features.vix),
      vix1d = COALESCE(EXCLUDED.vix1d, training_features.vix1d),
      vix9d = COALESCE(EXCLUDED.vix9d, training_features.vix9d),
      vvix = COALESCE(EXCLUDED.vvix, training_features.vvix),
      vix1d_vix_ratio = COALESCE(EXCLUDED.vix1d_vix_ratio, training_features.vix1d_vix_ratio),
      vix_vix9d_ratio = COALESCE(EXCLUDED.vix_vix9d_ratio, training_features.vix_vix9d_ratio),
      regime_zone = COALESCE(EXCLUDED.regime_zone, training_features.regime_zone),
      cluster_mult = COALESCE(EXCLUDED.cluster_mult, training_features.cluster_mult),
      dow_mult = COALESCE(EXCLUDED.dow_mult, training_features.dow_mult),
      dow_label = COALESCE(EXCLUDED.dow_label, training_features.dow_label),
      spx_open = COALESCE(EXCLUDED.spx_open, training_features.spx_open),
      sigma = COALESCE(EXCLUDED.sigma, training_features.sigma),
      hours_remaining = COALESCE(EXCLUDED.hours_remaining, training_features.hours_remaining),
      ic_ceiling = COALESCE(EXCLUDED.ic_ceiling, training_features.ic_ceiling),
      put_spread_ceiling = COALESCE(EXCLUDED.put_spread_ceiling, training_features.put_spread_ceiling),
      call_spread_ceiling = COALESCE(EXCLUDED.call_spread_ceiling, training_features.call_spread_ceiling),
      opening_range_signal = COALESCE(EXCLUDED.opening_range_signal, training_features.opening_range_signal),
      opening_range_pct_consumed = COALESCE(EXCLUDED.opening_range_pct_consumed, training_features.opening_range_pct_consumed),
      day_of_week = COALESCE(EXCLUDED.day_of_week, training_features.day_of_week),
      is_friday = COALESCE(EXCLUDED.is_friday, training_features.is_friday),
      is_event_day = COALESCE(EXCLUDED.is_event_day, training_features.is_event_day),
      mt_ncp_t1 = COALESCE(EXCLUDED.mt_ncp_t1, training_features.mt_ncp_t1),
      mt_npp_t1 = COALESCE(EXCLUDED.mt_npp_t1, training_features.mt_npp_t1),
      mt_ncp_t2 = COALESCE(EXCLUDED.mt_ncp_t2, training_features.mt_ncp_t2),
      mt_npp_t2 = COALESCE(EXCLUDED.mt_npp_t2, training_features.mt_npp_t2),
      mt_ncp_t3 = COALESCE(EXCLUDED.mt_ncp_t3, training_features.mt_ncp_t3),
      mt_npp_t3 = COALESCE(EXCLUDED.mt_npp_t3, training_features.mt_npp_t3),
      mt_ncp_t4 = COALESCE(EXCLUDED.mt_ncp_t4, training_features.mt_ncp_t4),
      mt_npp_t4 = COALESCE(EXCLUDED.mt_npp_t4, training_features.mt_npp_t4),
      spx_ncp_t1 = COALESCE(EXCLUDED.spx_ncp_t1, training_features.spx_ncp_t1),
      spx_npp_t1 = COALESCE(EXCLUDED.spx_npp_t1, training_features.spx_npp_t1),
      spx_ncp_t2 = COALESCE(EXCLUDED.spx_ncp_t2, training_features.spx_ncp_t2),
      spx_npp_t2 = COALESCE(EXCLUDED.spx_npp_t2, training_features.spx_npp_t2),
      spx_ncp_t3 = COALESCE(EXCLUDED.spx_ncp_t3, training_features.spx_ncp_t3),
      spx_npp_t3 = COALESCE(EXCLUDED.spx_npp_t3, training_features.spx_npp_t3),
      spx_ncp_t4 = COALESCE(EXCLUDED.spx_ncp_t4, training_features.spx_ncp_t4),
      spx_npp_t4 = COALESCE(EXCLUDED.spx_npp_t4, training_features.spx_npp_t4),
      spy_ncp_t1 = COALESCE(EXCLUDED.spy_ncp_t1, training_features.spy_ncp_t1),
      spy_npp_t1 = COALESCE(EXCLUDED.spy_npp_t1, training_features.spy_npp_t1),
      spy_ncp_t2 = COALESCE(EXCLUDED.spy_ncp_t2, training_features.spy_ncp_t2),
      spy_npp_t2 = COALESCE(EXCLUDED.spy_npp_t2, training_features.spy_npp_t2),
      qqq_ncp_t1 = COALESCE(EXCLUDED.qqq_ncp_t1, training_features.qqq_ncp_t1),
      qqq_npp_t1 = COALESCE(EXCLUDED.qqq_npp_t1, training_features.qqq_npp_t1),
      qqq_ncp_t2 = COALESCE(EXCLUDED.qqq_ncp_t2, training_features.qqq_ncp_t2),
      qqq_npp_t2 = COALESCE(EXCLUDED.qqq_npp_t2, training_features.qqq_npp_t2),
      spy_etf_ncp_t1 = COALESCE(EXCLUDED.spy_etf_ncp_t1, training_features.spy_etf_ncp_t1),
      spy_etf_npp_t1 = COALESCE(EXCLUDED.spy_etf_npp_t1, training_features.spy_etf_npp_t1),
      spy_etf_ncp_t2 = COALESCE(EXCLUDED.spy_etf_ncp_t2, training_features.spy_etf_ncp_t2),
      spy_etf_npp_t2 = COALESCE(EXCLUDED.spy_etf_npp_t2, training_features.spy_etf_npp_t2),
      qqq_etf_ncp_t1 = COALESCE(EXCLUDED.qqq_etf_ncp_t1, training_features.qqq_etf_ncp_t1),
      qqq_etf_npp_t1 = COALESCE(EXCLUDED.qqq_etf_npp_t1, training_features.qqq_etf_npp_t1),
      qqq_etf_ncp_t2 = COALESCE(EXCLUDED.qqq_etf_ncp_t2, training_features.qqq_etf_ncp_t2),
      qqq_etf_npp_t2 = COALESCE(EXCLUDED.qqq_etf_npp_t2, training_features.qqq_etf_npp_t2),
      zero_dte_ncp_t1 = COALESCE(EXCLUDED.zero_dte_ncp_t1, training_features.zero_dte_ncp_t1),
      zero_dte_npp_t1 = COALESCE(EXCLUDED.zero_dte_npp_t1, training_features.zero_dte_npp_t1),
      zero_dte_ncp_t2 = COALESCE(EXCLUDED.zero_dte_ncp_t2, training_features.zero_dte_ncp_t2),
      zero_dte_npp_t2 = COALESCE(EXCLUDED.zero_dte_npp_t2, training_features.zero_dte_npp_t2),
      delta_flow_total_t1 = COALESCE(EXCLUDED.delta_flow_total_t1, training_features.delta_flow_total_t1),
      delta_flow_dir_t1 = COALESCE(EXCLUDED.delta_flow_dir_t1, training_features.delta_flow_dir_t1),
      delta_flow_total_t2 = COALESCE(EXCLUDED.delta_flow_total_t2, training_features.delta_flow_total_t2),
      delta_flow_dir_t2 = COALESCE(EXCLUDED.delta_flow_dir_t2, training_features.delta_flow_dir_t2),
      flow_agreement_t1 = COALESCE(EXCLUDED.flow_agreement_t1, training_features.flow_agreement_t1),
      flow_agreement_t2 = COALESCE(EXCLUDED.flow_agreement_t2, training_features.flow_agreement_t2),
      etf_tide_divergence_t1 = COALESCE(EXCLUDED.etf_tide_divergence_t1, training_features.etf_tide_divergence_t1),
      etf_tide_divergence_t2 = COALESCE(EXCLUDED.etf_tide_divergence_t2, training_features.etf_tide_divergence_t2),
      ncp_npp_gap_spx_t1 = COALESCE(EXCLUDED.ncp_npp_gap_spx_t1, training_features.ncp_npp_gap_spx_t1),
      ncp_npp_gap_spx_t2 = COALESCE(EXCLUDED.ncp_npp_gap_spx_t2, training_features.ncp_npp_gap_spx_t2),
      gex_oi_t1 = COALESCE(EXCLUDED.gex_oi_t1, training_features.gex_oi_t1),
      gex_oi_t2 = COALESCE(EXCLUDED.gex_oi_t2, training_features.gex_oi_t2),
      gex_oi_t3 = COALESCE(EXCLUDED.gex_oi_t3, training_features.gex_oi_t3),
      gex_oi_t4 = COALESCE(EXCLUDED.gex_oi_t4, training_features.gex_oi_t4),
      gex_vol_t1 = COALESCE(EXCLUDED.gex_vol_t1, training_features.gex_vol_t1),
      gex_vol_t2 = COALESCE(EXCLUDED.gex_vol_t2, training_features.gex_vol_t2),
      gex_dir_t1 = COALESCE(EXCLUDED.gex_dir_t1, training_features.gex_dir_t1),
      gex_dir_t2 = COALESCE(EXCLUDED.gex_dir_t2, training_features.gex_dir_t2),
      gex_oi_slope = COALESCE(EXCLUDED.gex_oi_slope, training_features.gex_oi_slope),
      charm_oi_t1 = COALESCE(EXCLUDED.charm_oi_t1, training_features.charm_oi_t1),
      charm_oi_t2 = COALESCE(EXCLUDED.charm_oi_t2, training_features.charm_oi_t2),
      agg_net_gamma = COALESCE(EXCLUDED.agg_net_gamma, training_features.agg_net_gamma),
      dte0_net_charm = COALESCE(EXCLUDED.dte0_net_charm, training_features.dte0_net_charm),
      dte0_charm_pct = COALESCE(EXCLUDED.dte0_charm_pct, training_features.dte0_charm_pct),
      gamma_wall_above_dist = COALESCE(EXCLUDED.gamma_wall_above_dist, training_features.gamma_wall_above_dist),
      gamma_wall_above_mag = COALESCE(EXCLUDED.gamma_wall_above_mag, training_features.gamma_wall_above_mag),
      gamma_wall_below_dist = COALESCE(EXCLUDED.gamma_wall_below_dist, training_features.gamma_wall_below_dist),
      gamma_wall_below_mag = COALESCE(EXCLUDED.gamma_wall_below_mag, training_features.gamma_wall_below_mag),
      neg_gamma_nearest_dist = COALESCE(EXCLUDED.neg_gamma_nearest_dist, training_features.neg_gamma_nearest_dist),
      neg_gamma_nearest_mag = COALESCE(EXCLUDED.neg_gamma_nearest_mag, training_features.neg_gamma_nearest_mag),
      gamma_asymmetry = COALESCE(EXCLUDED.gamma_asymmetry, training_features.gamma_asymmetry),
      charm_slope = COALESCE(EXCLUDED.charm_slope, training_features.charm_slope),
      charm_max_pos_dist = COALESCE(EXCLUDED.charm_max_pos_dist, training_features.charm_max_pos_dist),
      charm_max_neg_dist = COALESCE(EXCLUDED.charm_max_neg_dist, training_features.charm_max_neg_dist),
      gamma_0dte_allexp_agree = COALESCE(EXCLUDED.gamma_0dte_allexp_agree, training_features.gamma_0dte_allexp_agree),
      charm_pattern = COALESCE(EXCLUDED.charm_pattern, training_features.charm_pattern),
      feature_completeness = COALESCE(EXCLUDED.feature_completeness, training_features.feature_completeness),
      prev_day_range_pts = COALESCE(EXCLUDED.prev_day_range_pts, training_features.prev_day_range_pts),
      prev_day_direction = COALESCE(EXCLUDED.prev_day_direction, training_features.prev_day_direction),
      prev_day_vix_change = COALESCE(EXCLUDED.prev_day_vix_change, training_features.prev_day_vix_change),
      prev_day_range_cat = COALESCE(EXCLUDED.prev_day_range_cat, training_features.prev_day_range_cat),
      realized_vol_5d = COALESCE(EXCLUDED.realized_vol_5d, training_features.realized_vol_5d),
      realized_vol_10d = COALESCE(EXCLUDED.realized_vol_10d, training_features.realized_vol_10d),
      rv_iv_ratio = COALESCE(EXCLUDED.rv_iv_ratio, training_features.rv_iv_ratio),
      vix_term_slope = COALESCE(EXCLUDED.vix_term_slope, training_features.vix_term_slope),
      vvix_percentile = COALESCE(EXCLUDED.vvix_percentile, training_features.vvix_percentile),
      event_type = COALESCE(EXCLUDED.event_type, training_features.event_type),
      is_fomc = COALESCE(EXCLUDED.is_fomc, training_features.is_fomc),
      is_opex = COALESCE(EXCLUDED.is_opex, training_features.is_opex),
      days_to_next_event = COALESCE(EXCLUDED.days_to_next_event, training_features.days_to_next_event),
      event_count = COALESCE(EXCLUDED.event_count, training_features.event_count),
      dp_total_premium = COALESCE(EXCLUDED.dp_total_premium, training_features.dp_total_premium),
      dp_cluster_count = COALESCE(EXCLUDED.dp_cluster_count, training_features.dp_cluster_count),
      dp_top_cluster_dist = COALESCE(EXCLUDED.dp_top_cluster_dist, training_features.dp_top_cluster_dist),
      dp_support_premium = COALESCE(EXCLUDED.dp_support_premium, training_features.dp_support_premium),
      dp_resistance_premium = COALESCE(EXCLUDED.dp_resistance_premium, training_features.dp_resistance_premium),
      dp_support_resistance_ratio = COALESCE(EXCLUDED.dp_support_resistance_ratio, training_features.dp_support_resistance_ratio),
      dp_concentration = COALESCE(EXCLUDED.dp_concentration, training_features.dp_concentration),
      max_pain_0dte = COALESCE(EXCLUDED.max_pain_0dte, training_features.max_pain_0dte),
      max_pain_dist = COALESCE(EXCLUDED.max_pain_dist, training_features.max_pain_dist),
      opt_call_volume = COALESCE(EXCLUDED.opt_call_volume, training_features.opt_call_volume),
      opt_put_volume = COALESCE(EXCLUDED.opt_put_volume, training_features.opt_put_volume),
      opt_call_oi = COALESCE(EXCLUDED.opt_call_oi, training_features.opt_call_oi),
      opt_put_oi = COALESCE(EXCLUDED.opt_put_oi, training_features.opt_put_oi),
      opt_call_premium = COALESCE(EXCLUDED.opt_call_premium, training_features.opt_call_premium),
      opt_put_premium = COALESCE(EXCLUDED.opt_put_premium, training_features.opt_put_premium),
      opt_bullish_premium = COALESCE(EXCLUDED.opt_bullish_premium, training_features.opt_bullish_premium),
      opt_bearish_premium = COALESCE(EXCLUDED.opt_bearish_premium, training_features.opt_bearish_premium),
      opt_call_vol_ask = COALESCE(EXCLUDED.opt_call_vol_ask, training_features.opt_call_vol_ask),
      opt_put_vol_bid = COALESCE(EXCLUDED.opt_put_vol_bid, training_features.opt_put_vol_bid),
      opt_vol_pcr = COALESCE(EXCLUDED.opt_vol_pcr, training_features.opt_vol_pcr),
      opt_oi_pcr = COALESCE(EXCLUDED.opt_oi_pcr, training_features.opt_oi_pcr),
      opt_premium_ratio = COALESCE(EXCLUDED.opt_premium_ratio, training_features.opt_premium_ratio),
      opt_call_vol_vs_avg30 = COALESCE(EXCLUDED.opt_call_vol_vs_avg30, training_features.opt_call_vol_vs_avg30),
      opt_put_vol_vs_avg30 = COALESCE(EXCLUDED.opt_put_vol_vs_avg30, training_features.opt_put_vol_vs_avg30),
      iv_open = COALESCE(EXCLUDED.iv_open, training_features.iv_open),
      iv_max = COALESCE(EXCLUDED.iv_max, training_features.iv_max),
      iv_range = COALESCE(EXCLUDED.iv_range, training_features.iv_range),
      iv_crush_rate = COALESCE(EXCLUDED.iv_crush_rate, training_features.iv_crush_rate),
      iv_spike_count = COALESCE(EXCLUDED.iv_spike_count, training_features.iv_spike_count),
      iv_at_t2 = COALESCE(EXCLUDED.iv_at_t2, training_features.iv_at_t2),
      pcr_open = COALESCE(EXCLUDED.pcr_open, training_features.pcr_open),
      pcr_max = COALESCE(EXCLUDED.pcr_max, training_features.pcr_max),
      pcr_min = COALESCE(EXCLUDED.pcr_min, training_features.pcr_min),
      pcr_range = COALESCE(EXCLUDED.pcr_range, training_features.pcr_range),
      pcr_trend_t1_t2 = COALESCE(EXCLUDED.pcr_trend_t1_t2, training_features.pcr_trend_t1_t2),
      pcr_spike_count = COALESCE(EXCLUDED.pcr_spike_count, training_features.pcr_spike_count),
      oic_net_oi_change = COALESCE(EXCLUDED.oic_net_oi_change, training_features.oic_net_oi_change),
      oic_call_oi_change = COALESCE(EXCLUDED.oic_call_oi_change, training_features.oic_call_oi_change),
      oic_put_oi_change = COALESCE(EXCLUDED.oic_put_oi_change, training_features.oic_put_oi_change),
      oic_oi_change_pcr = COALESCE(EXCLUDED.oic_oi_change_pcr, training_features.oic_oi_change_pcr),
      oic_net_premium = COALESCE(EXCLUDED.oic_net_premium, training_features.oic_net_premium),
      oic_call_premium = COALESCE(EXCLUDED.oic_call_premium, training_features.oic_call_premium),
      oic_put_premium = COALESCE(EXCLUDED.oic_put_premium, training_features.oic_put_premium),
      oic_ask_ratio = COALESCE(EXCLUDED.oic_ask_ratio, training_features.oic_ask_ratio),
      oic_multi_leg_pct = COALESCE(EXCLUDED.oic_multi_leg_pct, training_features.oic_multi_leg_pct),
      oic_top_strike_dist = COALESCE(EXCLUDED.oic_top_strike_dist, training_features.oic_top_strike_dist),
      oic_concentration = COALESCE(EXCLUDED.oic_concentration, training_features.oic_concentration),
      iv_ts_slope_0d_30d = COALESCE(EXCLUDED.iv_ts_slope_0d_30d, training_features.iv_ts_slope_0d_30d),
      iv_ts_contango = COALESCE(EXCLUDED.iv_ts_contango, training_features.iv_ts_contango),
      iv_ts_spread = COALESCE(EXCLUDED.iv_ts_spread, training_features.iv_ts_spread),
      uw_rv_30d = COALESCE(EXCLUDED.uw_rv_30d, training_features.uw_rv_30d),
      uw_iv_rv_spread = COALESCE(EXCLUDED.uw_iv_rv_spread, training_features.uw_iv_rv_spread),
      uw_iv_overpricing_pct = COALESCE(EXCLUDED.uw_iv_overpricing_pct, training_features.uw_iv_overpricing_pct),
      iv_rank = COALESCE(EXCLUDED.iv_rank, training_features.iv_rank),
      nope_t1 = COALESCE(EXCLUDED.nope_t1, training_features.nope_t1),
      nope_t2 = COALESCE(EXCLUDED.nope_t2, training_features.nope_t2),
      nope_t3 = COALESCE(EXCLUDED.nope_t3, training_features.nope_t3),
      nope_t4 = COALESCE(EXCLUDED.nope_t4, training_features.nope_t4),
      nope_am_mean = COALESCE(EXCLUDED.nope_am_mean, training_features.nope_am_mean),
      nope_am_sign_flips = COALESCE(EXCLUDED.nope_am_sign_flips, training_features.nope_am_sign_flips),
      nope_am_cum_delta = COALESCE(EXCLUDED.nope_am_cum_delta, training_features.nope_am_cum_delta)
  `;
}
