/**
 * Self-maintaining flow-regime baseline — computed ON READ from Neon.
 *
 * Resolves code-review finding #6: the committed flow-regime-baseline.json was
 * a frozen artifact that had to be regenerated by hand (offline, from the
 * Desktop full-tape parquet). This loader makes the baseline self-maintaining
 * straight from Neon:
 *
 *   - A daily post-close cron (capture-flow-regime-daily) accumulates each
 *     trading day's per-slot component sums into flow_regime_slot_daily (one
 *     row per (date, slot)).
 *   - This loader runs ONE aggregation query over that table and, per slot,
 *     computes the nine percentile breakpoints (1/5/10/25/50/75/90/95/99) of
 *     the two ratio metrics directly via percentile_cont — the SAME percentile
 *     grid the committed JSON uses, so the result is a drop-in replacement.
 *   - A slot's DB-computed breakpoints REPLACE the committed JSON ones ONLY
 *     when that slot has ≥ min_days_per_slot (15) days of history. Until then
 *     the slot falls back to the committed JSON breakpoints (cold-start seed).
 *
 * The committed flow-regime-baseline.json therefore stays as the cold-start
 * seed; everything self-maintains from Neon once each slot reaches ~15 trading
 * days of accumulation. No parquet, no Desktop dependency.
 *
 * The metric/percentile DEFINITIONS here MUST match api/_lib/flow-regime.ts
 * and the daily cron's bucketing — nd_tilt = nd_num / nd_den (guarded for a
 * zero denominator) and idx0dte_put_share = idx_put_premium / total_premium —
 * or the percentiles would be scored against an inconsistent distribution.
 */

import {
  FLOW_REGIME_BASELINE,
  type FlowRegimeBaseline,
  type FlowRegimeSlotBaseline,
} from './flow-regime.js';
import { numOrNull } from './numeric-coercion.js';

/**
 * Postgres `percentile_cont` fraction array, in the SAME order as the
 * committed baseline's `percentiles` grid ([1,5,10,25,50,75,90,95,99]). The
 * returned NUMERIC[] is therefore positionally aligned with
 * `FLOW_REGIME_BASELINE.percentiles`, so a DB-computed breakpoint array is a
 * drop-in replacement for the committed one. Derived from the committed grid
 * so the two can never drift.
 */
const PERCENTILE_FRACTIONS = FLOW_REGIME_BASELINE.percentiles.map(
  (p) => p / 100,
);

/**
 * One row of the per-slot aggregation. Postgres returns:
 *   - `slot`        — INT (number).
 *   - `n_days_nd`   — count of days with nd_den > 0 (BigInt or string).
 *   - `n_days_idx`  — count of days with total_premium > 0.
 *   - `nd_*` / `idx_*` — the percentile_cont(ARRAY[...]) results as a
 *     Postgres array; the Neon driver returns NUMERIC[] elements as strings.
 */
/** One element of a Postgres NUMERIC[] as the Neon driver returns it. */
type RawNumeric = string | number | null;

interface SlotPercentileRow {
  slot: number;
  n_days_nd: number | string | bigint | null;
  n_days_idx: number | string | bigint | null;
  nd_breakpoints: RawNumeric[] | null;
  idx_breakpoints: RawNumeric[] | null;
}

/**
 * Minimal SQL tag surface this loader needs — a single tagged-template call
 * returning rows. Mirrors how the cron consumes `getDb()` so callers can pass
 * the live `sql` instance (or a test double) without importing the Neon type.
 */
type SqlTag = (
  strings: TemplateStringsArray,
  ...values: unknown[]
) => Promise<unknown[]>;

export interface LoadedFlowRegimeBaseline {
  /**
   * A FlowRegimeBaseline ready to hand to `evaluateFlowRegime` — cloned from
   * the committed JSON with each LIVE slot's breakpoints replaced by the
   * DB-computed ones. Slots below the min-days threshold keep the JSON values.
   */
  baseline: FlowRegimeBaseline;
  /**
   * Set of slot indices whose breakpoints were replaced with DB-computed
   * values (≥ min_days_per_slot days). The cron stamps baseline_version 2 for
   * these and 1 for fallback slots, so a snapshot records which distribution
   * scored it.
   */
  liveSlots: ReadonlySet<number>;
}

/** Coerce a Postgres NUMERIC[] (driver may return string elements) to numbers, dropping non-finite. */
function coerceBreakpoints(raw: RawNumeric[] | null): number[] | null {
  if (raw == null) return null;
  const out: number[] = [];
  for (const v of raw) {
    const n = numOrNull(v);
    if (n === null) return null; // a NULL breakpoint = unusable distribution
    out.push(n);
  }
  return out;
}

/**
 * Build the self-maintaining baseline by computing per-slot percentile
 * breakpoints from flow_regime_slot_daily, falling back per-slot to the
 * committed JSON until a slot has ≥ min_days_per_slot days.
 *
 * ONE aggregation query. Per slot it computes, in a single pass:
 *   - the count of days usable for each metric (nd_den > 0 / total_premium > 0),
 *   - percentile_cont(ARRAY[...]) WITHIN GROUP (ORDER BY ratio) for each metric,
 *     guarding a zero denominator with NULLIF so a degenerate day is excluded
 *     rather than poisoning the ordering.
 *
 * Robust to an empty table: every slot falls back to the committed JSON and
 * `liveSlots` is empty (so the cron stamps baseline_version 1 everywhere —
 * identical to the pre-self-maintaining behavior).
 */
export async function loadFlowRegimeBaseline(
  sql: SqlTag,
): Promise<LoadedFlowRegimeBaseline> {
  const minDays = FLOW_REGIME_BASELINE.min_days_per_slot;

  // percentile_cont over the per-day ratio, computed per slot. NULLIF guards a
  // zero denominator (that day contributes NULL → dropped by percentile_cont
  // and by the COUNT filter). The fractions array is positionally aligned with
  // the committed `percentiles` grid.
  const rows = (await sql`
    SELECT
      slot,
      COUNT(*) FILTER (WHERE nd_den > 0)        AS n_days_nd,
      COUNT(*) FILTER (WHERE total_premium > 0) AS n_days_idx,
      percentile_cont(${PERCENTILE_FRACTIONS}::float8[]) WITHIN GROUP (
        ORDER BY nd_num / NULLIF(nd_den, 0)
      ) AS nd_breakpoints,
      percentile_cont(${PERCENTILE_FRACTIONS}::float8[]) WITHIN GROUP (
        ORDER BY idx_put_premium / NULLIF(total_premium, 0)
      ) AS idx_breakpoints
    FROM flow_regime_slot_daily
    GROUP BY slot
  `) as SlotPercentileRow[];

  const bySlot = new Map<number, SlotPercentileRow>();
  for (const r of rows) bySlot.set(r.slot, r);

  const liveSlots = new Set<number>();

  // Clone the committed baseline; replace per-slot breakpoints when live.
  const slots: FlowRegimeSlotBaseline[] = FLOW_REGIME_BASELINE.slots.map(
    (jsonSlot) => {
      const row = bySlot.get(jsonSlot.slot);
      if (!row) return { ...jsonSlot };

      const nDaysNd = numOrNull(row.n_days_nd) ?? 0;
      const nDaysIdx = numOrNull(row.n_days_idx) ?? 0;
      const ndBreaks = coerceBreakpoints(row.nd_breakpoints);
      const idxBreaks = coerceBreakpoints(row.idx_breakpoints);

      // A slot goes live only when BOTH metrics have ≥ minDays usable days AND
      // produced a full, finite breakpoint array. Otherwise keep the JSON seed.
      const ndLive =
        nDaysNd >= minDays &&
        ndBreaks?.length === jsonSlot.nd_tilt_breakpoints.length;
      const idxLive =
        nDaysIdx >= minDays &&
        idxBreaks?.length === jsonSlot.idx0dte_put_share_breakpoints.length;

      if (!ndLive && !idxLive) return { ...jsonSlot };

      // n_days drives the evaluator's own thin-baseline gate; use the metric
      // depth that actually went live (max of the two live counts).
      const liveNDays = Math.max(ndLive ? nDaysNd : 0, idxLive ? nDaysIdx : 0);

      liveSlots.add(jsonSlot.slot);
      return {
        slot: jsonSlot.slot,
        n_days: Math.max(jsonSlot.n_days, liveNDays),
        nd_tilt_breakpoints:
          ndLive && ndBreaks ? ndBreaks : jsonSlot.nd_tilt_breakpoints,
        idx0dte_put_share_breakpoints:
          idxLive && idxBreaks
            ? idxBreaks
            : jsonSlot.idx0dte_put_share_breakpoints,
      };
    },
  );

  const baseline: FlowRegimeBaseline = {
    ...FLOW_REGIME_BASELINE,
    generated_from:
      liveSlots.size > 0
        ? `Live from Neon flow_regime_slot_daily (${liveSlots.size}/${FLOW_REGIME_BASELINE.slots.length} slots ≥${minDays}d); remaining slots seeded from committed flow-regime-baseline.json.`
        : FLOW_REGIME_BASELINE.generated_from,
    slots,
  };

  return { baseline, liveSlots };
}
