/**
 * Web Push fan-out helper for the SPXW Interval B/A alert v2.
 *
 * Reads all rows from `push_subscriptions`, posts the payload via the
 * `web-push` SDK using VAPID auth, and cleans up subscriptions whose
 * endpoint returns 410 Gone / 404 Not Found (browser profile reset,
 * user revoked permission, etc.) so the table doesn't grow stale.
 *
 * Returns `{ sent, expired, failed }` counts so the calling endpoint
 * can log fan-out health.
 *
 * VAPID env vars (set on Vercel via `vercel env add`):
 *   VAPID_PUBLIC_KEY  — generated by `npx web-push generate-vapid-keys`
 *   VAPID_PRIVATE_KEY — same generation step
 *   VAPID_SUBJECT     — `mailto:<your-email>` (push services require it)
 *
 * Spec: docs/superpowers/specs/interval-ba-push-v2-2026-05-12.md.
 */

import webpush from 'web-push';
import { getDb } from './db.js';
import logger from './logger.js';

export interface PushPayload {
  /** Notification title — shown bold in the system notification. */
  title: string;
  /** Notification body — second-line text. */
  body: string;
  /** Dedupe tag so a re-fire replaces rather than stacks. */
  tag?: string;
  /** True keeps the notification visible until the user interacts. */
  requireInteraction?: boolean;
  /** Optional deep link the click handler can use. */
  url?: string;
}

export interface FanOutResult {
  /** Subscriptions the push service accepted. */
  sent: number;
  /** Subscriptions removed because the endpoint returned 410/404. */
  expired: number;
  /** Subscriptions that errored on a non-cleanup status (5xx, network). */
  failed: number;
}

interface SubscriptionRow {
  id: number;
  endpoint: string;
  p256dh_key: string;
  auth_key: string;
}

let vapidConfigured = false;

/**
 * Normalize a VAPID key for the web-push SDK.
 *
 * Web Push (RFC 8292) requires URL-safe base64 *without* padding. Common
 * operator footguns this fixes idempotently:
 *   - Trailing `=` padding (the web-push SDK rejects it with
 *     `Vapid public key must be a URL safe Base 64 (without "=")` —
 *     SENTRY-EMERALD-DESERT-7W, 9 events).
 *   - Standard-alphabet `+` / `/` from `openssl base64` instead of
 *     URL-safe `-` / `_`.
 *   - Surrounding whitespace from a copy-paste.
 *
 * The transformation is information-preserving, so re-running
 * `npx web-push generate-vapid-keys` (which already emits the canonical
 * form) keeps working identically.
 */
function normalizeVapidKey(key: string): string {
  let out = key.trim().replace(/\+/g, '-').replace(/\//g, '_');
  while (out.endsWith('=')) out = out.slice(0, -1);
  return out;
}

/**
 * Configure web-push with VAPID credentials. Idempotent — runs once per
 * Vercel function cold start. Throws if any required env var is missing
 * so the caller surfaces a 500 rather than silently no-op'ing.
 */
function ensureVapidConfigured(): void {
  if (vapidConfigured) return;
  const subject = process.env.VAPID_SUBJECT;
  const publicKey = process.env.VAPID_PUBLIC_KEY;
  const privateKey = process.env.VAPID_PRIVATE_KEY;
  if (!subject || !publicKey || !privateKey) {
    throw new Error(
      'web-push not configured: set VAPID_SUBJECT, VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY',
    );
  }
  webpush.setVapidDetails(
    subject,
    normalizeVapidKey(publicKey),
    normalizeVapidKey(privateKey),
  );
  vapidConfigured = true;
}

/**
 * Send `payload` to every device subscribed by the owner. Subscriptions
 * that return 410/404 are deleted from the table so they don't keep
 * eating fan-out attempts.
 */
export async function sendPushToOwner(
  payload: PushPayload,
): Promise<FanOutResult> {
  ensureVapidConfigured();
  const sql = getDb();
  const rawRows = await sql`
    SELECT id, endpoint, p256dh_key, auth_key
    FROM push_subscriptions
  `;
  const rows = rawRows as unknown as SubscriptionRow[];
  if (rows.length === 0) {
    return { sent: 0, expired: 0, failed: 0 };
  }

  const serialized = JSON.stringify(payload);
  const result: FanOutResult = { sent: 0, expired: 0, failed: 0 };
  const expiredIds: number[] = [];

  // Sequential fan-out — at single-owner scale (1-3 devices) the
  // throughput gain of Promise.all isn't worth the extra failure-mode
  // analysis. Each push call is ~100-300ms; total stays well under
  // the Vercel function budget.
  for (const row of rows) {
    try {
      await webpush.sendNotification(
        {
          endpoint: row.endpoint,
          keys: { p256dh: row.p256dh_key, auth: row.auth_key },
        },
        serialized,
        { TTL: 60 },
      );
      result.sent += 1;
    } catch (err) {
      const statusCode = (err as { statusCode?: number }).statusCode;
      if (statusCode === 410 || statusCode === 404) {
        // Browser revoked or rotated the subscription — drop the row.
        expiredIds.push(row.id);
        result.expired += 1;
      } else {
        result.failed += 1;
        logger.warn(
          { err, endpoint: row.endpoint, statusCode },
          'web-push send failed',
        );
      }
    }
  }

  if (expiredIds.length > 0) {
    await sql`
      DELETE FROM push_subscriptions
      WHERE id = ANY(${expiredIds})
    `;
  }

  // Stamp last_used_at on the rows that succeeded so an admin can see
  // which devices are alive. Best-effort — failure here doesn't change
  // the fan-out result (the pushes already landed).
  if (result.sent > 0) {
    try {
      const liveIds = rows
        .filter((r) => !expiredIds.includes(r.id))
        .map((r) => r.id);
      await sql`
        UPDATE push_subscriptions
        SET last_used_at = NOW()
        WHERE id = ANY(${liveIds})
      `;
    } catch (err) {
      logger.warn({ err }, 'push_subscriptions last_used_at update failed');
    }
  }

  return result;
}

// Exported for tests so the module-level VAPID cache can be reset
// between cases without re-importing the module.
export function __resetVapidForTests(): void {
  vapidConfigured = false;
}
