// @vitest-environment node
//
// Tests for the v2 lottery scoring model. The TS file is regenerated by
// scripts/sync_lottery_score_weights_v2.py from ml/output/lottery_score_weights.json,
// so we pin the SHAPE of the API (alignment gate, dte universe gate,
// null-safe quintiles, tier classification) rather than specific weight
// values — which shift on every model retrain.

import { describe, expect, it } from 'vitest';
import {
  assignQuintile,
  computeLotteryScoreV2,
  lotteryScoreTierV2,
  COMPOSITE_BONUSES_V2,
  LOTTERY_TIER_THRESHOLDS_V2,
  GAMMA_QUINTILE_BOUNDARIES,
  ASK_PCT_QUINTILE_BOUNDARIES,
  VOL_OI_QUINTILE_BOUNDARIES,
  TOD_WEIGHTS_DOW_OVERRIDES_V2,
  TOD_WEIGHTS_V2,
  LOTTERY_TICKER_WEIGHTS_V2,
} from '../_lib/lottery-score-weights-v2.js';

// The per-ticker weights are regenerated on every nightly model retrain, so any
// assertion about the *difference* between two tickers' scores must derive the
// ticker-weight delta from the live table — never hardcode a magnitude. These
// helpers isolate the pure per-feature ticker contribution that survives when a
// composite does NOT fire, so the composite tests can assert the mechanism
// (bonus applied additively on top of the per-feature weights) independent of
// the nightly weight values.
const tickerWeight = (t: string): number => LOTTERY_TICKER_WEIGHTS_V2[t] ?? 0;
const tickerDelta = (a: string, b: string): number =>
  tickerWeight(a) - tickerWeight(b);

describe('computeLotteryScoreV2 — hard alignment gate', () => {
  it('returns null when isAligned is false', () => {
    expect(
      computeLotteryScoreV2({
        ticker: 'AMZN',
        tod: 'AM_open',
        dte: 1,
        volOiWindow: 0.12,
        gammaAtTrigger: 0.05,
        triggerAskPct: 0.55,
        optionType: 'C',
        isAligned: false,
      }),
    ).toBeNull();
  });

  it('returns null when DTE is outside {0,1,2,3}', () => {
    expect(
      computeLotteryScoreV2({
        ticker: 'AMZN',
        tod: 'AM_open',
        dte: 4,
        volOiWindow: 0.12,
        gammaAtTrigger: 0.05,
        triggerAskPct: 0.55,
        optionType: 'C',
        isAligned: true,
      }),
    ).toBeNull();
  });

  it('returns a non-null integer for an aligned in-universe fire', () => {
    const score = computeLotteryScoreV2({
      ticker: 'AMZN',
      tod: 'AM_open',
      dte: 1,
      volOiWindow: 0.12,
      gammaAtTrigger: 0.05,
      triggerAskPct: 0.55,
      optionType: 'C',
      isAligned: true,
    });
    expect(score).not.toBeNull();
    expect(Number.isInteger(score)).toBe(true);
  });
});

describe('computeLotteryScoreV2 — null continuous features contribute 0', () => {
  it('omits all 3 quintile contributions when their inputs are null', () => {
    // Compare a fire with all-null continuous features against one with
    // present features — the gap MUST equal the sum of the 3 quintile
    // contributions. Identical fires apart from those 3 fields:
    const withFeatures = computeLotteryScoreV2({
      ticker: 'AMZN',
      tod: 'AM_open',
      dte: 1,
      volOiWindow: 0.12,
      gammaAtTrigger: 0.05,
      triggerAskPct: 0.55,
      optionType: 'C',
      isAligned: true,
    });
    const withoutFeatures = computeLotteryScoreV2({
      ticker: 'AMZN',
      tod: 'AM_open',
      dte: 1,
      volOiWindow: null,
      gammaAtTrigger: null,
      triggerAskPct: null,
      optionType: 'C',
      isAligned: true,
    });
    // Both must be non-null because alignment + dte are satisfied
    expect(withFeatures).not.toBeNull();
    expect(withoutFeatures).not.toBeNull();
    // The categorical-only score is a valid integer (could be positive,
    // zero, or negative depending on weights — just must not throw)
    expect(Number.isInteger(withoutFeatures)).toBe(true);
  });
});

describe('assignQuintile', () => {
  it('returns 0 for values below the first boundary', () => {
    expect(assignQuintile(0.001, VOL_OI_QUINTILE_BOUNDARIES)).toBe(0);
  });

  it('returns 4 for values at or above the last boundary', () => {
    const lastBoundary =
      VOL_OI_QUINTILE_BOUNDARIES[VOL_OI_QUINTILE_BOUNDARIES.length - 1] ?? 0;
    expect(assignQuintile(lastBoundary, VOL_OI_QUINTILE_BOUNDARIES)).toBe(4);
    expect(assignQuintile(lastBoundary * 10, VOL_OI_QUINTILE_BOUNDARIES)).toBe(
      4,
    );
  });

  it('returns a quintile between 0 and 4 for any input', () => {
    for (const v of [-1, 0, 0.05, 0.1, 0.5, 1, 100]) {
      const q = assignQuintile(v, VOL_OI_QUINTILE_BOUNDARIES);
      expect(q).toBeGreaterThanOrEqual(0);
      expect(q).toBeLessThanOrEqual(4);
      expect(Number.isInteger(q)).toBe(true);
    }
  });
});

describe('lotteryScoreTierV2', () => {
  it('treats null as tier3', () => {
    expect(lotteryScoreTierV2(null)).toBe('tier3');
  });

  it('classifies scores at or above t1 as tier1', () => {
    expect(lotteryScoreTierV2(LOTTERY_TIER_THRESHOLDS_V2.t1)).toBe('tier1');
    expect(lotteryScoreTierV2(LOTTERY_TIER_THRESHOLDS_V2.t1 + 100)).toBe(
      'tier1',
    );
  });

  it('classifies scores in [t2, t1) as tier2', () => {
    if (LOTTERY_TIER_THRESHOLDS_V2.t1 > LOTTERY_TIER_THRESHOLDS_V2.t2) {
      expect(lotteryScoreTierV2(LOTTERY_TIER_THRESHOLDS_V2.t2)).toBe('tier2');
      expect(lotteryScoreTierV2(LOTTERY_TIER_THRESHOLDS_V2.t1 - 1)).toBe(
        'tier2',
      );
    }
  });

  it('classifies scores below t2 as tier3', () => {
    expect(lotteryScoreTierV2(LOTTERY_TIER_THRESHOLDS_V2.t2 - 1)).toBe('tier3');
    expect(lotteryScoreTierV2(-1000)).toBe('tier3');
  });
});

describe('LOTTERY_TIER_THRESHOLDS_V2 shape', () => {
  it('has numeric t1 and t2 with t1 > t2', () => {
    expect(typeof LOTTERY_TIER_THRESHOLDS_V2.t1).toBe('number');
    expect(typeof LOTTERY_TIER_THRESHOLDS_V2.t2).toBe('number');
    expect(LOTTERY_TIER_THRESHOLDS_V2.t1).toBeGreaterThan(
      LOTTERY_TIER_THRESHOLDS_V2.t2,
    );
  });
});

describe('computeLotteryScoreV2 — Monday DOW override', () => {
  const baseArgs = {
    ticker: 'AMZN',
    dte: 1,
    volOiWindow: null,
    gammaAtTrigger: null,
    triggerAskPct: null,
    optionType: 'C' as const,
    isAligned: true,
  };

  it('Monday override exists in TOD_WEIGHTS_DOW_OVERRIDES_V2', () => {
    expect('Monday' in TOD_WEIGHTS_DOW_OVERRIDES_V2).toBe(true);
    const mon = TOD_WEIGHTS_DOW_OVERRIDES_V2['Monday']!;
    // Lineage finding: LUNCH should be positive, AM_open should be lower
    // than global (global AM_open=+4; Monday AM_open must be < that).
    expect(mon.LUNCH).toBeGreaterThan(0);
    expect(mon.AM_open).toBeLessThan(TOD_WEIGHTS_V2.AM_open);
  });

  it('Monday AM_open score differs from non-Monday AM_open score', () => {
    const mondayScore = computeLotteryScoreV2({
      ...baseArgs,
      tod: 'AM_open',
      dayOfWeek: 'Monday',
    });
    const tuesdayScore = computeLotteryScoreV2({
      ...baseArgs,
      tod: 'AM_open',
      dayOfWeek: 'Tuesday',
    });
    // Tuesday has no override → uses global AM_open weight → scores differ
    expect(mondayScore).not.toBeNull();
    expect(tuesdayScore).not.toBeNull();
    expect(mondayScore).not.toBe(tuesdayScore);
  });

  it('Monday LUNCH score differs from non-Monday LUNCH score', () => {
    const mondayScore = computeLotteryScoreV2({
      ...baseArgs,
      tod: 'LUNCH',
      dayOfWeek: 'Monday',
    });
    const globalScore = computeLotteryScoreV2({
      ...baseArgs,
      tod: 'LUNCH',
    });
    expect(mondayScore).not.toBeNull();
    expect(globalScore).not.toBeNull();
    // Monday LUNCH is positive; global LUNCH is negative → Monday scores higher
    expect(mondayScore!).toBeGreaterThan(globalScore!);
  });

  it('falls back to global TOD weights when dayOfWeek is not in overrides', () => {
    const wednesdayScore = computeLotteryScoreV2({
      ...baseArgs,
      tod: 'AM_open',
      dayOfWeek: 'Wednesday',
    });
    const noOverrideScore = computeLotteryScoreV2({
      ...baseArgs,
      tod: 'AM_open',
    });
    // Both use the global TOD table → identical score
    expect(wednesdayScore).toBe(noOverrideScore);
  });

  it('falls back to global TOD weights when dayOfWeek is omitted', () => {
    const withoutDow = computeLotteryScoreV2({
      ...baseArgs,
      tod: 'PM',
    });
    const withTuesday = computeLotteryScoreV2({
      ...baseArgs,
      tod: 'PM',
      dayOfWeek: 'Tuesday',
    });
    expect(withoutDow).toBe(withTuesday);
  });
});

describe('computeLotteryScoreV2 — composite bonuses/penalties', () => {
  // Base args that are definitely aligned and in-universe.
  const aligned = {
    dte: 1,
    optionType: 'C' as const,
    isAligned: true,
    volOiWindow: null,
    gammaAtTrigger: null,
    triggerAskPct: null,
  };

  it('COMPOSITE_BONUSES_V2 has the expected 7 entries from the 2026-05-22 mining report', () => {
    expect(COMPOSITE_BONUSES_V2).toHaveLength(7);
  });

  it('winning composites all have positive bonus', () => {
    const winners = COMPOSITE_BONUSES_V2.filter((e) => e.winRate >= 0.9);
    expect(winners.length).toBeGreaterThan(0);
    for (const w of winners) {
      expect(w.bonus).toBeGreaterThan(0);
    }
  });

  it('losing composites all have negative bonus', () => {
    const losers = COMPOSITE_BONUSES_V2.filter((e) => e.winRate === 0);
    expect(losers.length).toBeGreaterThan(0);
    for (const l of losers) {
      expect(l.bonus).toBeLessThan(0);
    }
  });

  it('SNDK + AM_open + gamma_q=0 fire scores higher than an identical non-matching fire', () => {
    // gamma_q=0 requires gammaAtTrigger < GAMMA_QUINTILE_BOUNDARIES[0]
    const gammaQ0 = GAMMA_QUINTILE_BOUNDARIES[0]! * 0.5; // safely inside Q0
    const sndkScore = computeLotteryScoreV2({
      ...aligned,
      ticker: 'SNDK',
      tod: 'AM_open',
      gammaAtTrigger: gammaQ0,
    });
    // Same fire but different ticker — composite does not fire.
    const noMatchScore = computeLotteryScoreV2({
      ...aligned,
      ticker: 'AMZN',
      tod: 'AM_open',
      gammaAtTrigger: gammaQ0,
    });
    expect(sndkScore).not.toBeNull();
    expect(noMatchScore).not.toBeNull();
    // SNDK gets its composite bonus on top of the same per-feature weights.
    // The delta vs an AMZN fire is therefore: (SNDK ticker weight − AMZN ticker
    // weight) + the composite bonus. Both terms are derived from the live tables
    // so a nightly retrain that shifts either magnitude does not break this.
    const sndkBonus = COMPOSITE_BONUSES_V2.find(
      (e) => e.match.ticker === 'SNDK',
    )!.bonus;
    expect(sndkScore! - noMatchScore!).toBe(
      tickerDelta('SNDK', 'AMZN') + sndkBonus,
    );
  });

  it('WDC + ask_pct_q=0 fire scores lower than an identical non-matching fire', () => {
    // ask_pct_q=0 requires triggerAskPct < ASK_PCT_QUINTILE_BOUNDARIES[0]
    const askQ0 = ASK_PCT_QUINTILE_BOUNDARIES[0]! * 0.5;
    const wdcScore = computeLotteryScoreV2({
      ...aligned,
      ticker: 'WDC',
      tod: 'AM_open',
      triggerAskPct: askQ0,
    });
    const noMatchScore = computeLotteryScoreV2({
      ...aligned,
      ticker: 'AMZN',
      tod: 'AM_open',
      triggerAskPct: askQ0,
    });
    expect(wdcScore).not.toBeNull();
    expect(noMatchScore).not.toBeNull();
    // WDC gets its composite penalty on top of the same per-feature weights.
    // Delta vs AMZN = (WDC ticker weight − AMZN ticker weight) + the penalty;
    // both derived from the live tables, robust to nightly retrains.
    const wdcPenalty = COMPOSITE_BONUSES_V2.find(
      (e) => e.match.ticker === 'WDC',
    )!.bonus;
    expect(wdcScore! - noMatchScore!).toBe(
      tickerDelta('WDC', 'AMZN') + wdcPenalty,
    );
  });

  it('composite does not fire when only some match keys agree', () => {
    // SNDK + AM_open but gamma is Q4, not Q0 — composite must NOT fire.
    const gammaQ4 = GAMMA_QUINTILE_BOUNDARIES[3]! * 2; // safely in Q4
    const withoutComposite = computeLotteryScoreV2({
      ...aligned,
      ticker: 'SNDK',
      tod: 'AM_open',
      gammaAtTrigger: gammaQ4,
    });
    // Same fire but AMZN — definitely no composite.
    const baselineScore = computeLotteryScoreV2({
      ...aligned,
      ticker: 'AMZN',
      tod: 'AM_open',
      gammaAtTrigger: gammaQ4,
    });
    expect(withoutComposite).not.toBeNull();
    expect(baselineScore).not.toBeNull();
    // Only the ticker weight differs (SNDK vs AMZN); no composite bonus fires,
    // so the gap is the pure per-feature ticker delta from the live table.
    expect(withoutComposite! - baselineScore!).toBe(
      tickerDelta('SNDK', 'AMZN'),
    );
  });

  it('null quintile features do not spuriously match a string-keyed composite', () => {
    // A fire with null gammaAtTrigger: gamma_q label is "null".
    // The SNDK composite requires gamma_q="0" — must not match.
    const sndkNullGamma = computeLotteryScoreV2({
      ...aligned,
      ticker: 'SNDK',
      tod: 'AM_open',
      gammaAtTrigger: null,
    });
    const amznNullGamma = computeLotteryScoreV2({
      ...aligned,
      ticker: 'AMZN',
      tod: 'AM_open',
      gammaAtTrigger: null,
    });
    expect(sndkNullGamma).not.toBeNull();
    expect(amznNullGamma).not.toBeNull();
    // Only the ticker-weight difference — no composite (null gamma_q label is
    // "null", which the string-keyed SNDK composite cannot match).
    expect(sndkNullGamma! - amznNullGamma!).toBe(tickerDelta('SNDK', 'AMZN'));
  });
});

// NOTE: V2.2 Phase D context feature tests removed 2026-05-23.
// Walk-forward backtest found the 7 context features (spx_spot_charm_oi,
// spx_spot_vanna_oi, mkt_tide_ncp, mkt_tide_npp, mkt_tide_diff,
// mkt_tide_otm_diff, spx_spot_gamma_oi) are systematically overfit:
// removing them improves OOS tier1 Sharpe by +0.099. The function signature
// retains no context parameters; score_components.py handles them as dormant
// (contributes 0 when the weights JSON has no context blocks).
