// @vitest-environment node

import { describe, expect, it } from 'vitest';
import {
  computeLotteryScore,
  gammaScoreAdjustment,
  lotteryScoreTier,
  LOTTERY_TICKER_WEIGHTS,
  LOTTERY_TIER_THRESHOLDS,
} from '../_lib/lottery-score-weights.js';

describe('computeLotteryScore', () => {
  it('returns the maximum score for a top-tier 0DTE call', () => {
    // SNDK (10) + 0DTE (5) + price ≤ $0.50 (5) + AM_open (3) + call (2)
    // Use a tier-1 ticker (weight 10) so this asserts the actual ceiling;
    // USO is tier-2 (weight 7) and would only sum to 22.
    expect(
      computeLotteryScore({
        ticker: 'SNDK',
        mode: 'A_intraday_0DTE',
        entryPrice: 0.4,
        tod: 'AM_open',
        optionType: 'C',
      }),
    ).toBe(25);
  });

  it('respects the price threshold ladder (≤$0.50 wins over ≤$1.00)', () => {
    // SNDK (10) + 0DTE (5) + price ≤ $0.50 (5, NOT 3) + MID (2) + call (2) = 24
    expect(
      computeLotteryScore({
        ticker: 'SNDK',
        mode: 'A_intraday_0DTE',
        entryPrice: 0.5,
        tod: 'MID',
        optionType: 'C',
      }),
    ).toBe(24);
  });

  it('zeroes price weight when entry price exceeds $1.00', () => {
    // SNDK (10) + 0DTE (5) + price > $1.00 (0) + MID (2) + call (2) = 19
    expect(
      computeLotteryScore({
        ticker: 'SNDK',
        mode: 'A_intraday_0DTE',
        entryPrice: 2.5,
        tod: 'MID',
        optionType: 'C',
      }),
    ).toBe(19);
  });

  it('returns 0 for an unweighted ticker / multi-day put / lunch / pricey', () => {
    // unknown ticker (0) + multi-day (0) + price > $1.00 (0) + LUNCH (0) + put (0)
    expect(
      computeLotteryScore({
        ticker: 'AAPL',
        mode: 'B_multi_day_DTE1_3',
        entryPrice: 4.5,
        tod: 'LUNCH',
        optionType: 'P',
      }),
    ).toBe(0);
  });

  it('does not give 0DTE credit to OUT_OF_UNIVERSE mode', () => {
    // Use an unweighted ticker so the assertion isolates the mode bucket.
    expect(
      computeLotteryScore({
        ticker: 'AAPL',
        mode: 'OUT_OF_UNIVERSE',
        entryPrice: 0.3,
        tod: 'AM_open',
        optionType: 'C',
      }),
    ).toBe(0 + 0 + 5 + 3 + 2);
  });

  it('has at least one ticker at each weight tier', () => {
    // Pin the weights-table SHAPE rather than specific tickers — the
    // file is auto-regenerated by `make refit` (see its docstring),
    // so naming a specific weight-5 ticker breaks every refit that
    // reshuffles the bottom of the cohort. AAPL is the canonical
    // not-in-universe sentinel; that one's safe to name.
    const weights = Object.values(LOTTERY_TICKER_WEIGHTS);
    expect(weights).toContain(10);
    expect(weights).toContain(7);
    expect(weights).toContain(5);
    expect(LOTTERY_TICKER_WEIGHTS.AAPL).toBeUndefined();
  });
});

describe('lotteryScoreTier', () => {
  it('classifies score ≥18 as tier1', () => {
    expect(lotteryScoreTier(LOTTERY_TIER_THRESHOLDS.tier1MinScore)).toBe(
      'tier1',
    );
    expect(lotteryScoreTier(25)).toBe('tier1');
  });

  it('classifies 12 ≤ score < 18 as tier2', () => {
    expect(lotteryScoreTier(LOTTERY_TIER_THRESHOLDS.tier2MinScore)).toBe(
      'tier2',
    );
    expect(lotteryScoreTier(17)).toBe('tier2');
  });

  it('classifies score <12 as tier3', () => {
    expect(lotteryScoreTier(11)).toBe('tier3');
    expect(lotteryScoreTier(0)).toBe('tier3');
  });

  it('treats null score as tier3', () => {
    expect(lotteryScoreTier(null)).toBe('tier3');
  });
});

// ============================================================
// fireCountScoreAdjustment was retired in commit 16fd1655. The
// adjustment is now a stored DB column (`fire_count_score_adjustment`,
// migration #167) read directly by api/lottery-finder.ts:1005, so
// the read-time TS helper is no longer needed and the test was
// deleted with it. Bucket boundaries (−3/−1/0/+1/+2) are now owned
// by the migration SQL — see api/_lib/db-migrations.ts:#167 if you
// need to verify them.
// ============================================================

// ============================================================
// gammaScoreAdjustment — outside-the-box winner-feature bonus
// (basis: docs/tmp/gamma-deep-dive-findings-2026-05-17.md)
// ============================================================

describe('gammaScoreAdjustment', () => {
  it('awards +1 for gamma >= 0.025 on a non-excluded ticker', () => {
    expect(gammaScoreAdjustment(0.025, 'TSLA')).toBe(1);
    expect(gammaScoreAdjustment(0.05, 'NVDA')).toBe(1);
    expect(gammaScoreAdjustment(1.2, 'META')).toBe(1);
  });

  it('returns 0 below the 0.025 threshold (even on a non-excluded ticker)', () => {
    expect(gammaScoreAdjustment(0.024, 'TSLA')).toBe(0);
    expect(gammaScoreAdjustment(0.001, 'NVDA')).toBe(0);
  });

  it('returns 0 for SPY regardless of gamma magnitude (signal reverses)', () => {
    expect(gammaScoreAdjustment(0.05, 'SPY')).toBe(0);
    expect(gammaScoreAdjustment(1.0, 'SPY')).toBe(0);
  });

  it('returns 0 for USO regardless of gamma magnitude (signal reverses)', () => {
    expect(gammaScoreAdjustment(0.05, 'USO')).toBe(0);
    expect(gammaScoreAdjustment(0.5, 'USO')).toBe(0);
  });

  it('returns 0 for null gamma (no data — fail-open semantics)', () => {
    expect(gammaScoreAdjustment(null, 'TSLA')).toBe(0);
  });

  it('returns 0 for non-finite gamma (defensive)', () => {
    expect(gammaScoreAdjustment(Number.NaN, 'TSLA')).toBe(0);
    expect(gammaScoreAdjustment(Number.POSITIVE_INFINITY, 'TSLA')).toBe(0);
  });
});
