// @vitest-environment node
//
// Tests for the v2 lottery scoring model. The TS file is regenerated by
// scripts/sync_lottery_score_weights_v2.py from ml/output/lottery_score_weights.json,
// so we pin the SHAPE of the API (alignment gate, dte universe gate,
// null-safe quintiles, tier classification) rather than specific weight
// values — which shift on every model retrain.

import { describe, expect, it } from 'vitest';
import {
  assignQuintile,
  computeLotteryScoreV2,
  lotteryScoreTierV2,
  LOTTERY_TIER_THRESHOLDS_V2,
  VOL_OI_QUINTILE_BOUNDARIES,
} from '../_lib/lottery-score-weights-v2.js';

describe('computeLotteryScoreV2 — hard alignment gate', () => {
  it('returns null when isAligned is false', () => {
    expect(
      computeLotteryScoreV2({
        ticker: 'AMZN',
        tod: 'AM_open',
        dte: 1,
        volOiWindow: 0.12,
        gammaAtTrigger: 0.05,
        triggerAskPct: 0.55,
        optionType: 'C',
        isAligned: false,
      }),
    ).toBeNull();
  });

  it('returns null when DTE is outside {0,1,2,3}', () => {
    expect(
      computeLotteryScoreV2({
        ticker: 'AMZN',
        tod: 'AM_open',
        dte: 4,
        volOiWindow: 0.12,
        gammaAtTrigger: 0.05,
        triggerAskPct: 0.55,
        optionType: 'C',
        isAligned: true,
      }),
    ).toBeNull();
  });

  it('returns a non-null integer for an aligned in-universe fire', () => {
    const score = computeLotteryScoreV2({
      ticker: 'AMZN',
      tod: 'AM_open',
      dte: 1,
      volOiWindow: 0.12,
      gammaAtTrigger: 0.05,
      triggerAskPct: 0.55,
      optionType: 'C',
      isAligned: true,
    });
    expect(score).not.toBeNull();
    expect(Number.isInteger(score)).toBe(true);
  });
});

describe('computeLotteryScoreV2 — null continuous features contribute 0', () => {
  it('omits all 3 quintile contributions when their inputs are null', () => {
    // Compare a fire with all-null continuous features against one with
    // present features — the gap MUST equal the sum of the 3 quintile
    // contributions. Identical fires apart from those 3 fields:
    const withFeatures = computeLotteryScoreV2({
      ticker: 'AMZN',
      tod: 'AM_open',
      dte: 1,
      volOiWindow: 0.12,
      gammaAtTrigger: 0.05,
      triggerAskPct: 0.55,
      optionType: 'C',
      isAligned: true,
    });
    const withoutFeatures = computeLotteryScoreV2({
      ticker: 'AMZN',
      tod: 'AM_open',
      dte: 1,
      volOiWindow: null,
      gammaAtTrigger: null,
      triggerAskPct: null,
      optionType: 'C',
      isAligned: true,
    });
    // Both must be non-null because alignment + dte are satisfied
    expect(withFeatures).not.toBeNull();
    expect(withoutFeatures).not.toBeNull();
    // The categorical-only score is a valid integer (could be positive,
    // zero, or negative depending on weights — just must not throw)
    expect(Number.isInteger(withoutFeatures)).toBe(true);
  });
});

describe('assignQuintile', () => {
  it('returns 0 for values below the first boundary', () => {
    expect(assignQuintile(0.001, VOL_OI_QUINTILE_BOUNDARIES)).toBe(0);
  });

  it('returns 4 for values at or above the last boundary', () => {
    const lastBoundary =
      VOL_OI_QUINTILE_BOUNDARIES[VOL_OI_QUINTILE_BOUNDARIES.length - 1] ?? 0;
    expect(assignQuintile(lastBoundary, VOL_OI_QUINTILE_BOUNDARIES)).toBe(4);
    expect(assignQuintile(lastBoundary * 10, VOL_OI_QUINTILE_BOUNDARIES)).toBe(
      4,
    );
  });

  it('returns a quintile between 0 and 4 for any input', () => {
    for (const v of [-1, 0, 0.05, 0.1, 0.5, 1, 100]) {
      const q = assignQuintile(v, VOL_OI_QUINTILE_BOUNDARIES);
      expect(q).toBeGreaterThanOrEqual(0);
      expect(q).toBeLessThanOrEqual(4);
      expect(Number.isInteger(q)).toBe(true);
    }
  });
});

describe('lotteryScoreTierV2', () => {
  it('treats null as tier3', () => {
    expect(lotteryScoreTierV2(null)).toBe('tier3');
  });

  it('classifies scores at or above t1 as tier1', () => {
    expect(lotteryScoreTierV2(LOTTERY_TIER_THRESHOLDS_V2.t1)).toBe('tier1');
    expect(lotteryScoreTierV2(LOTTERY_TIER_THRESHOLDS_V2.t1 + 100)).toBe(
      'tier1',
    );
  });

  it('classifies scores in [t2, t1) as tier2', () => {
    if (LOTTERY_TIER_THRESHOLDS_V2.t1 > LOTTERY_TIER_THRESHOLDS_V2.t2) {
      expect(lotteryScoreTierV2(LOTTERY_TIER_THRESHOLDS_V2.t2)).toBe('tier2');
      expect(lotteryScoreTierV2(LOTTERY_TIER_THRESHOLDS_V2.t1 - 1)).toBe(
        'tier2',
      );
    }
  });

  it('classifies scores below t2 as tier3', () => {
    expect(lotteryScoreTierV2(LOTTERY_TIER_THRESHOLDS_V2.t2 - 1)).toBe('tier3');
    expect(lotteryScoreTierV2(-1000)).toBe('tier3');
  });
});

describe('LOTTERY_TIER_THRESHOLDS_V2 shape', () => {
  it('has numeric t1 and t2 with t1 > t2', () => {
    expect(typeof LOTTERY_TIER_THRESHOLDS_V2.t1).toBe('number');
    expect(typeof LOTTERY_TIER_THRESHOLDS_V2.t2).toBe('number');
    expect(LOTTERY_TIER_THRESHOLDS_V2.t1).toBeGreaterThan(
      LOTTERY_TIER_THRESHOLDS_V2.t2,
    );
  });
});
