/// <reference lib="webworker" />
/**
 * Custom service worker — Phase 2A.1 of FuturesGammaPlaybook Web Push.
 *
 * Moved from `generateSW` (auto-generated by `vite-plugin-pwa`) to
 * `injectManifest` so we can ship the `push` / `notificationclick` /
 * `pushsubscriptionchange` handlers below. All previously auto-generated
 * behavior is reproduced here 1:1 — nothing was dropped silently.
 *
 * ## Preserved Workbox behavior (was in `vite.config.ts > workbox`)
 *
 * - `skipWaiting: true` / `clientsClaim: true` — handled by the `install`
 *   / `activate` listeners at the bottom of this file.
 * - `cleanupOutdatedCaches: true` — handled by `cleanupOutdatedCaches()`.
 * - `globPatterns: ['**\/*.{js,css,html,png,woff2}']` — now lives in
 *   `vite.config.ts > VitePWA > injectManifest.globPatterns`.
 * - `navigateFallback: '/index.html'` with denylist for `/api/` and the
 *   BotID challenge path — `createHandlerBoundToURL('/index.html')` +
 *   `NavigationRoute` with `denylist` below.
 * - Runtime `NetworkOnly` bypass for `/api/` (GET + POST) — prevents
 *   Chrome's 5-min SW fetch-event timeout from killing long-running
 *   Claude Opus analysis calls at 300s. Registered via `registerRoute`.
 * - `StaleWhileRevalidate` for `/vix-data.json` — served from
 *   `vix-data-cache`.
 * - `StaleWhileRevalidate` for `fonts.googleapis.com` stylesheets —
 *   `google-fonts-stylesheets` cache, 10 entries / 1 year.
 * - `CacheFirst` for `fonts.gstatic.com` webfonts — `google-fonts-webfonts`
 *   cache, 30 entries / 1 year.
 *
 * ## New behavior (Phase 2A.1)
 *
 * - `push` — render a notification from the `AlertEvent` payload, using
 *   `event.id` as `tag` so repeated edges for the same alert collapse
 *   instead of stacking.
 * - `notificationclick` — focus an existing client tab (deep-linked to
 *   the FuturesGammaPlaybook anchor) or open a new one.
 * - `pushsubscriptionchange` — re-subscribe and POST the new subscription
 *   to `/api/push/subscribe`. The endpoint doesn't exist yet (Phase 2A.2);
 *   404s are swallowed and the frontend hook will re-subscribe on next
 *   app open.
 */

import {
  cleanupOutdatedCaches,
  createHandlerBoundToURL,
  precacheAndRoute,
} from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing';
import {
  CacheFirst,
  NetworkOnly,
  StaleWhileRevalidate,
} from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';

import type { AlertEvent } from './utils/futures-gamma/alerts';

declare const self: ServiceWorkerGlobalScope;

// ── Precache (globPatterns from injectManifest config) ──────────────
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// ── SPA navigation fallback ─────────────────────────────────────────
// Matches old workbox.navigateFallback + navigateFallbackDenylist.
registerRoute(
  new NavigationRoute(createHandlerBoundToURL('/index.html'), {
    denylist: [/^\/api\//, /^\/149e9513-01fa-4fb0-aad4-566afd725d1b\//],
  }),
);

// ── /api/ bypass ────────────────────────────────────────────────────
// Prevents Chrome's 5-min SW fetch-event timeout from killing long
// Claude Opus analysis calls at 300s. NetworkOnly short-circuits the
// SW's FetchEvent lifecycle entirely.
registerRoute(/^\/api\//, new NetworkOnly(), 'GET');
registerRoute(/^\/api\//, new NetworkOnly(), 'POST');

// ── /vix-data.json — StaleWhileRevalidate ───────────────────────────
registerRoute(
  /\/vix-data\.json$/,
  new StaleWhileRevalidate({ cacheName: 'vix-data-cache' }),
);

// ── Google Fonts stylesheets — StaleWhileRevalidate ─────────────────
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/,
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365,
      }),
    ],
  }),
);

// ── Google Fonts webfonts — CacheFirst ──────────────────────────────
registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/,
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 60 * 60 * 24 * 365,
      }),
    ],
  }),
);

// ── Lifecycle ───────────────────────────────────────────────────────
// Switched from auto-skipWaiting (old `registerType: 'autoUpdate'`) to
// prompt-on-demand. A new SW now installs and stays in the `waiting`
// state until the page calls `updateSW(true)` (which posts SKIP_WAITING
// here). That gives the user a chance to finish what they were doing
// before the bundle reload yanks them out of context. clients.claim()
// stays so the new SW takes control of any open tabs immediately on
// activate, which fires the page's existing controllerchange listener.
self.addEventListener('message', (event) => {
  if ((event.data as { type?: string } | null)?.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// ── Push event ──────────────────────────────────────────────────────
// Deep-link target for notification clicks. The FuturesGammaPlaybook
// renders inside the single-page App at the `#futures-gamma-playbook`
// anchor.
const PLAYBOOK_URL = '/#futures-gamma-playbook';

interface PushNotificationData {
  url: string;
  eventId: string;
}

self.addEventListener('push', (event) => {
  const fallback = (): Promise<void> =>
    self.registration.showNotification('New alert', {
      body: 'A new futures gamma playbook alert is available.',
      icon: '/icon-192.png',
      badge: '/icon-192.png',
      data: {
        url: PLAYBOOK_URL,
        eventId: 'unknown',
      } satisfies PushNotificationData,
    });

  if (!event.data) {
    event.waitUntil(fallback());
    return;
  }

  const work = (async (): Promise<void> => {
    try {
      const alert = event.data!.json() as AlertEvent;
      await self.registration.showNotification(alert.title, {
        body: alert.body,
        tag: alert.id,
        icon: '/icon-192.png',
        badge: '/icon-192.png',
        data: {
          url: PLAYBOOK_URL,
          eventId: alert.id,
        } satisfies PushNotificationData,
      });
    } catch {
      await fallback();
    }
  })();

  event.waitUntil(work);
});

// ── Notification click ──────────────────────────────────────────────
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const data = event.notification.data as PushNotificationData | undefined;
  const url = data?.url ?? PLAYBOOK_URL;

  event.waitUntil(
    (async (): Promise<void> => {
      const clientList = await self.clients.matchAll({
        type: 'window',
        includeUncontrolled: true,
      });
      const existing = clientList.at(0);
      if (existing) {
        await existing.focus();
        return;
      }
      await self.clients.openWindow(url);
    })(),
  );
});

// ── Subscription rotation ───────────────────────────────────────────
// The browser may rotate push subscriptions (expiry, key roll, etc.).
// Re-subscribe with the same `applicationServerKey` and POST the new
// endpoint to the backend. The backend endpoint is Phase 2A.2 — until
// it lands, 404s are swallowed and the frontend hook will re-subscribe
// on next app open.
self.addEventListener('pushsubscriptionchange', (event) => {
  const subscriptionChangeEvent = event as PushSubscriptionChangeEvent;

  event.waitUntil(
    (async (): Promise<void> => {
      const oldSubscription = subscriptionChangeEvent.oldSubscription;
      const applicationServerKey =
        oldSubscription?.options.applicationServerKey ?? null;
      if (!applicationServerKey) return;

      try {
        const newSubscription = await self.registration.pushManager.subscribe({
          userVisibleOnly: true,
          applicationServerKey,
        });

        try {
          await fetch('/api/push/subscribe', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              subscription: newSubscription.toJSON(),
              rotatedFrom: oldSubscription?.endpoint ?? null,
            }),
          });
        } catch {
          // Endpoint not yet deployed (Phase 2A.2) — silent no-op.
        }
      } catch {
        // Re-subscription failed — the frontend hook will retry on
        // next app open.
      }
    })(),
  );
});

/**
 * Shape of the `pushsubscriptionchange` event. Not yet part of
 * `lib.webworker.d.ts`, so we declare the minimum surface we use.
 */
interface PushSubscriptionChangeEvent extends ExtendableEvent {
  readonly oldSubscription: PushSubscription | null;
  readonly newSubscription: PushSubscription | null;
}
